# Generated by Django 5.0.4 on 2024-04-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookindex', '0004_alter_book_price_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bookindex/book_images/'),
        ),
    ]
